import type { MaterialIssue } from "../types";

const normalized = (value: unknown) => String(value || "").trim().toLowerCase();

/** Auto-generated production handoffs remain valid for stock/accounting but are not general consumable issues. */
export function isAutoProductionInterFirmIssue(issue: MaterialIssue) {
  return normalized(issue.interFirmFlow) === "yes"
    && normalized(issue.autoGenerated) === "yes"
    && normalized(issue.sourceTransactionType) === "production processing";
}
