type FirmWiseReceipt = {
  firmId?: unknown;
  sourceFirmId?: unknown;
  destinationFirmId?: unknown;
  autoGenerated?: unknown;
};

export function shouldExcludeFirmWiseNpdReceipt(
  receipt: FirmWiseReceipt,
  unitOneFirmId: string,
  unitTwoFirmId: string,
) {
  const destinationFirmId = String(receipt.destinationFirmId || receipt.firmId || "").trim();
  return Boolean(unitOneFirmId && unitTwoFirmId)
    && String(receipt.sourceFirmId || "").trim() === unitOneFirmId
    && destinationFirmId === unitTwoFirmId
    && String(receipt.autoGenerated || "").trim().toLowerCase() === "yes";
}
