import { useMemo, useState } from "react";
import { ExternalLink, Search } from "lucide-react";
import { useData } from "../hooks/useData";
import { useNpdItems } from "../hooks/useNpdItems";
import { ExcelExport } from "../components/ExcelExport";
import type { PrintingQcCheck, Production } from "../types";

const COLUMNS = ["Job. No.", "Date", "Party Name", "Item Name", "ERP Code", "Previous Customer Complaint", "Required Length", "Achieved Length", "Min length", "Max Length", "Required Width", "Achieved Width", "Width Min", "Width Max", "Required Height", "Achieved Height", "Height Min", "Height Max", "CS Act / CS STD", "B.GSM", "Box Weight (Grams)", "Artwork", "Printing Artwork Check", "Printing Color Check", "Box Squaring Check", "Flap Gap Check", "Joint Pasting / Delamination Check", "Remarks [IF ANY]", "Box Photo [FRONT]", "Box Photo [BACK]", "Result", "QC Person Name", "PDI TIME", "Ply", "Standard CS", "STD CS", "Actual CS"] as const;
type Row = Record<string, string | number>; const s = (v: unknown) => String(v ?? "").trim(); const key = (v: unknown) => s(v).toLowerCase(); const n = (v: unknown): string | number => v === "" || v == null ? "" : Number.isFinite(Number(v)) ? Number(v) : s(v); const same = (a: unknown, b: unknown) => key(a) === key(b); const isUrl = (v: unknown) => /^https?:\/\//i.test(s(v)); const LinkCell = ({ value }: { value: unknown }) => isUrl(value) ? <button type="button" onClick={() => window.open(s(value), "_blank", "noopener,noreferrer")} className="inline-flex items-center gap-1 rounded bg-indigo-600 px-2 py-1 font-bold text-white"><ExternalLink size={13} />Open</button> : <>{s(value)}</>;

export function PdiReport() {
  const [productions] = useData<Production>("productions", [], { firmScope: "all" }); const [checks] = useData<PrintingQcCheck>("printing_qc_checks", []); const items = useNpdItems(); const [search, setSearch] = useState(""); const [jobFilter, setJobFilter] = useState(""); const [partyFilter, setPartyFilter] = useState(""); const [itemFilter, setItemFilter] = useState(""); const [resultFilter, setResultFilter] = useState(""); const [visible, setVisible] = useState<number[]>(() => COLUMNS.map((_, i) => i));
  const rows = useMemo<Row[]>(() => productions.filter((p) => p.status !== "Cancelled").map((p) => { const job = s(p.transactionNo || p.jobCardNo); const q = checks.filter((item) => same(item.jobNo, job)).sort((a, b) => s(a.timestamp).localeCompare(s(b.timestamp))).at(-1); const erp = s(p.erpCode || q?.erp); const item = items.find((i: any) => key(i.id) === key(p.itemId) || key(i.id) === key(p.npdId) || key(i.erp) === key(erp)); const itemName = s((p as any).itemName || item?.name || q?.itemName); const result = q ? ([q.systemAutoCorrection1, q.systemAutoCorrection2, q.systemAutoCorrection3, q.systemAutoCorrection4].some(Boolean) ? "QC HOLD" : "QC PASS") : ""; return { "Job. No.": job, Date: s(p.date).slice(0, 10), "Party Name": s(p.companyName || q?.partyName), "Item Name": itemName, "ERP Code": erp, "Previous Customer Complaint": s(q?.previousCustomerComplaintWarning), "Required Length": n(q?.lengthSpec || item?.length || p.length), "Achieved Length": n(q?.lengthId), "Min length": "", "Max Length": "", "Required Width": n(q?.widthSpec || item?.breadth || p.breadth), "Achieved Width": n(q?.widthId), "Width Min": "", "Width Max": "", "Required Height": n(q?.heightSpec || item?.height || p.height), "Achieved Height": n(q?.heightId), "Height Min": "", "Height Max": "", "CS Act / CS STD": q?.csAchieved !== "" && q?.csStandard !== "" ? `${q?.csAchieved || ""} / ${q?.csStandard || ""}` : "", "B.GSM": n((p as any).gsm || (p as any).boardGsm || item?.gsm), "Box Weight (Grams)": n(q?.boxWeightGrams), Artwork: s(item?.artwork || q?.standardArtwork), "Printing Artwork Check": s(q?.standardArtwork), "Printing Color Check": [q?.printingColor1Standard, q?.colour1Actual, q?.printingColour2Standard, q?.colour2Actual].filter(Boolean).join(" / "), "Box Squaring Check": s(q?.column40), "Flap Gap Check": s(q?.column41), "Joint Pasting / Delamination Check": s(q?.column42), "Remarks [IF ANY]": s(q?.column43), "Box Photo [FRONT]": s(q?.photo), "Box Photo [BACK]": "", Result: result, "QC Person Name": s(q?.qcPerson), "PDI TIME": s(q?.timestamp), Ply: n((p as any).ply || item?.ply), "Standard CS": n(q?.csStandard), "STD CS": n(q?.qcMasterCsSpec || q?.npdSheetCsSpec), "Actual CS": n(q?.csAchieved) }; }).filter((r) => (!jobFilter || r["Job. No."] === jobFilter) && (!partyFilter || r["Party Name"] === partyFilter) && (!itemFilter || r["Item Name"] === itemFilter) && (!resultFilter || r.Result === resultFilter) && (!search.trim() || Object.values(r).some((v) => key(v).includes(key(search))))), [checks, itemFilter, items, partyFilter, productions, resultFilter, search, jobFilter]);
  const options = useMemo(() => ({ jobs: [...new Set(rows.map((r) => s(r["Job. No."])))].sort(), parties: [...new Set(rows.map((r) => s(r["Party Name"])).filter(Boolean))].sort(), items: [...new Set(rows.map((r) => s(r["Item Name"])).filter(Boolean))].sort(), results: [...new Set(rows.map((r) => s(r.Result)).filter(Boolean))].sort() }), [rows]); const selected = visible.filter((i) => i < COLUMNS.length); const exportRows = rows.map((r) => Object.fromEntries(selected.map((i) => [COLUMNS[i], r[COLUMNS[i]] ?? ""]))); const clear = () => { setSearch(""); setJobFilter(""); setPartyFilter(""); setItemFilter(""); setResultFilter(""); };
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-black pb-3"><h2 className="text-xl font-bold uppercase">PDI Report</h2><ExcelExport data={exportRows} fileName="PDI_Report" sheetName="PDI Report" /></div><div className="grid grid-cols-1 gap-2 rounded border border-black bg-white p-3 md:grid-cols-6"><div className="relative md:col-span-2"><Search className="absolute left-2 top-2.5 text-slate-500" size={16} /><input className="w-full rounded border border-black py-2 pl-8 pr-2" placeholder="Search job / party / item / ERP / QC" value={search} onChange={(e) => setSearch(e.target.value)} /></div>{[[jobFilter, setJobFilter, "All Jobs", options.jobs], [partyFilter, setPartyFilter, "All Parties", options.parties], [itemFilter, setItemFilter, "All Items", options.items], [resultFilter, setResultFilter, "All Results", options.results]].map(([value, setter, label, values]: any) => <select key={label} value={value} onChange={(e) => setter(e.target.value)} className="rounded border border-black p-2 text-sm"><option value="">{label}</option>{values.map((v: string) => <option key={v}>{v}</option>)}</select>)}<button type="button" onClick={clear} className="rounded border border-black px-3 py-2 font-bold">Clear Filters</button><details className="relative"><summary className="cursor-pointer rounded border border-black px-3 py-2 font-bold">Columns ({selected.length}/{COLUMNS.length})</summary><div className="absolute right-0 z-20 mt-1 max-h-96 w-80 overflow-auto rounded border-2 border-black bg-white p-3 shadow-lg">{COLUMNS.map((column, i) => <label key={column} className="flex items-center gap-2 py-1 text-xs"><input type="checkbox" checked={selected.includes(i)} onChange={() => setVisible((v) => v.includes(i) ? v.filter((x) => x !== i) : [...v, i].sort((a, b) => a - b))} /><span>{column}</span></label>)}</div></details></div><div className="overflow-auto rounded border-2 border-black bg-white"><table className="min-w-[2200px] border-collapse text-[11px]"><thead><tr className="bg-fuchsia-800 text-white">{selected.map((i) => <th key={COLUMNS[i]} className="whitespace-nowrap border border-black px-2 py-2 text-left">{COLUMNS[i]}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, ri) => <tr key={`${row["Job. No."]}-${ri}`} className="odd:bg-white even:bg-slate-50">{selected.map((i) => <td key={COLUMNS[i]} className="whitespace-nowrap border border-black px-2 py-2">{["Artwork", "Box Photo [FRONT]", "Box Photo [BACK]"].includes(COLUMNS[i]) ? <LinkCell value={row[COLUMNS[i]]} /> : row[COLUMNS[i]] ?? ""}</td>)}</tr>) : <tr><td colSpan={selected.length || 1} className="p-8 text-center">No PDI records found.</td></tr>}</tbody></table></div></div>;
}
