import { FormEvent, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, Plus, Save, Search } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import { Select } from "../components/Select";
import { useAuth } from "../auth/AuthContext";
import { useData } from "../hooks/useData";
import { useNpdItems } from "../hooks/useNpdItems";
import type { PrintingStereoRecord } from "../types";

const input = "w-full rounded border-2 border-black bg-white px-3 py-2";
const text = (value: unknown) => String(value ?? "").trim();

export function PrintingStereoForm() {
  const navigate = useNavigate(); const { user } = useAuth(); const items = useNpdItems();
  const [, , , api] = useData<PrintingStereoRecord>("printing_stereo_records", [], { firmScope: "all" });
  const [form, setForm] = useState({ npdId: "", erpCode: "", partyName: "", itemName: "", location: "", blockNo: "", updatedBy: text(user?.name || user?.userId || user?.email) });
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const options = useMemo(() => items.map((item: any) => ({ value: text(item.id), label: `${text(item.erp)} - ${text(item.name)}`, searchText: `${text(item.erp)} ${text(item.name)} ${text(item.customer)}` })).filter(option => option.value), [items]);
  const selectNpd = (npdId: string) => { const item = items.find((value: any) => text(value.id) === npdId) as any; setForm(current => ({ ...current, npdId, erpCode: text(item?.erp), partyName: text(item?.customer), itemName: text(item?.name) })); };
  const save = async (event: FormEvent) => { event.preventDefault(); setMessage(""); if (!form.npdId || !form.erpCode || !form.location.trim() || !form.blockNo.trim()) return setMessage("ERP Code, Location, and Block No. are required."); setSaving(true); try { await api.addItem({ ...form, id: `STEREO-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, location: form.location.trim(), blockNo: form.blockNo.trim(), updateTimestamp: new Date().toISOString() }); navigate("/quality/printing-stereo", { state: { message: "Printing Stereo record saved successfully." } }); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save Printing Stereo record."); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-5xl space-y-5 pb-8"><div className="flex items-center justify-between border-b border-black pb-3"><div><h2 className="text-xl font-bold uppercase">Printing Stereo Form</h2><p className="text-sm text-slate-600">Create a printing stereo record against an NPD ERP.</p></div><button type="button" onClick={() => navigate("/quality/printing-stereo")} className="inline-flex items-center gap-2 rounded border-2 border-black bg-white px-4 py-2 font-bold"><ArrowLeft size={17}/>Back</button></div>{message && <div className="flex items-center gap-2 rounded border border-amber-700 bg-amber-100 p-3 font-bold"><CheckCircle2 size={18}/>{message}</div>}<form onSubmit={save} className="rounded border-2 border-black bg-white p-5"><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><label className="space-y-1 md:col-span-2"><b>ERP Code / NPD *</b><Select value={form.npdId} onChange={selectNpd} options={options} placeholder="Search ERP or Item Name"/></label><label className="space-y-1"><b>ERP Code</b><input className={`${input} bg-gray-400 text-gray-900`} style={{ backgroundColor: "#9ca3af", color: "#111827" }} readOnly value={form.erpCode}/></label><label className="space-y-1"><b>Party Name</b><input className={`${input} bg-gray-400 text-gray-900`} style={{ backgroundColor: "#9ca3af", color: "#111827" }} readOnly value={form.partyName}/></label><label className="space-y-1"><b>Item Name</b><input className={`${input} bg-gray-400 text-gray-900`} style={{ backgroundColor: "#9ca3af", color: "#111827" }} readOnly value={form.itemName}/></label><label className="space-y-1"><b>Location *</b><input className={input} value={form.location} onChange={event => setForm(current => ({ ...current, location: event.target.value }))}/></label><label className="space-y-1"><b>Block No. *</b><input className={input} value={form.blockNo} onChange={event => setForm(current => ({ ...current, blockNo: event.target.value }))}/></label><label className="space-y-1"><b>Updated By</b><input className={`${input} bg-gray-400 text-gray-900`} style={{ backgroundColor: "#9ca3af", color: "#111827" }} value={form.updatedBy} onChange={event => setForm(current => ({ ...current, updatedBy: event.target.value }))}/></label></div><div className="mt-5 flex justify-end"><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded bg-cyan-700 px-5 py-3 font-bold text-white disabled:opacity-60"><Save size={17}/>{saving ? "Saving..." : "Save Printing Stereo"}</button></div></form></div>;
}

export function PrintingStereoMaster() {
  const location = useLocation(); const navigate = useNavigate(); const [records, , loading] = useData<PrintingStereoRecord>("printing_stereo_records", [], { firmScope: "all" }); const [search, setSearch] = useState("");
  const message = text((location.state as { message?: string } | null)?.message); const filtered = useMemo(() => { const query = search.toLowerCase().trim(); return records.filter(record => !query || `${record.erpCode} ${record.partyName} ${record.itemName} ${record.location} ${record.blockNo}`.toLowerCase().includes(query)).sort((a, b) => text(b.updateTimestamp).localeCompare(text(a.updateTimestamp))); }, [records, search]);
  return <div className="space-y-5 pb-8"><div className="flex items-center justify-between border-b border-black pb-3"><h2 className="text-xl font-bold uppercase">Printing Stereo Master</h2><button type="button" onClick={() => navigate("/quality/printing-stereo/form")} className="inline-flex items-center gap-2 rounded bg-cyan-700 px-4 py-2 font-bold text-white"><Plus size={18}/>Add</button></div>{message && <div className="rounded border border-emerald-700 bg-emerald-100 p-3 font-bold">{message}</div>}<div className="rounded border-2 border-black bg-white p-3"><div className="relative max-w-xl"><Search className="absolute left-3 top-2.5 text-slate-500" size={18}/><input className="w-full rounded border-2 border-black py-2 pl-10 pr-3" placeholder="Search ERP, party, item, location, block..." value={search} onChange={event => setSearch(event.target.value)}/></div></div><div className="overflow-auto rounded border-2 border-black bg-white"><table className="min-w-[1000px] w-full border-collapse text-sm"><thead className="bg-cyan-800 text-white"><tr>{["Sl. No.","ERP Code","Party Name","Item Name","Location","Block No.","Updated By","Updated Timestamp"].map(header => <th key={header} className="border border-black p-2 text-left">{header}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-6 text-center">Loading...</td></tr> : filtered.length ? filtered.map((record, index) => <tr key={record.id}><td className="border border-black p-2">{index + 1}</td><td className="border border-black p-2 font-bold">{record.erpCode}</td><td className="border border-black p-2">{record.partyName}</td><td className="border border-black p-2">{record.itemName}</td><td className="border border-black p-2">{record.location}</td><td className="border border-black p-2">{record.blockNo}</td><td className="border border-black p-2">{record.updatedBy}</td><td className="border border-black p-2">{record.updateTimestamp || "-"}</td></tr>) : <tr><td colSpan={8} className="p-6 text-center">No Printing Stereo records found.</td></tr>}</tbody></table></div></div>;
}


