import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import { useLocation } from "react-router-dom";
import { useData } from "../hooks/useData";
import type { PrintingStereoRecord } from "../types";

const text = (value: unknown) => String(value ?? "").trim();
export function PrintingStereoMaster() {
  const location = useLocation(); const [records, , loading] = useData<PrintingStereoRecord>("printing_stereo_records", [], { firmScope: "all" }); const [search, setSearch] = useState("");
  const message = text((location.state as { message?: string } | null)?.message); const filtered = useMemo(() => { const query = search.toLowerCase().trim(); return records.filter(record => !query || `${record.erpCode} ${record.partyName} ${record.itemName} ${record.location} ${record.blockNo}`.toLowerCase().includes(query)).sort((a, b) => text(b.updateTimestamp).localeCompare(text(a.updateTimestamp))); }, [records, search]);
  return <div className="space-y-5 pb-8"><div className="flex items-center justify-between border-b border-black pb-3"><h2 className="text-xl font-bold uppercase">Printing Stereo Records</h2></div>{message && <div className="rounded border border-emerald-700 bg-emerald-100 p-3 font-bold">{message}</div>}<div className="rounded border-2 border-black bg-white p-3"><div className="relative max-w-xl"><Search className="absolute left-3 top-2.5 text-slate-500" size={18}/><input className="w-full rounded border-2 border-black py-2 pl-10 pr-3" placeholder="Search ERP, party, item, location, block..." value={search} onChange={event => setSearch(event.target.value)}/></div></div><div className="overflow-auto rounded border-2 border-black bg-white"><table className="min-w-[1000px] w-full border-collapse text-sm"><thead className="bg-cyan-800 text-white"><tr>{["Sl. No.","ERP Code","Party Name","Item Name","Location","Block No.","Updated By","Updated Timestamp"].map(header => <th key={header} className="border border-black p-2 text-left">{header}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-6 text-center">Loading...</td></tr> : filtered.length ? filtered.map((record, index) => <tr key={record.id}><td className="border border-black p-2">{index + 1}</td><td className="border border-black p-2 font-bold">{record.erpCode}</td><td className="border border-black p-2">{record.partyName}</td><td className="border border-black p-2">{record.itemName}</td><td className="border border-black p-2">{record.location}</td><td className="border border-black p-2">{record.blockNo}</td><td className="border border-black p-2">{record.updatedBy}</td><td className="border border-black p-2">{record.updateTimestamp || "-"}</td></tr>) : <tr><td colSpan={8} className="p-6 text-center">No Printing Stereo records found.</td></tr>}</tbody></table></div></div>;
}


