import { useMemo, useState } from "react";
import { useData } from "../hooks/useData";
import { useNpdItems } from "../hooks/useNpdItems";
import { Select } from "../components/Select";
import type { Firm, Item, QcBlockLocationMaster, QcBlockRecord } from "../types";

const input = "w-full rounded border-2 border-black bg-white px-3 py-2";
const clean = (v: unknown) => String(v ?? "").trim();
export function QcBlockRecord() {
  const [records, , loading, api] = useData<QcBlockRecord>("qc_block_records", [], { firmScope: "all" });
  const [locations] = useData<QcBlockLocationMaster>("qc_block_location_masters", [], { firmScope: "all" });
  const [firms] = useData<Firm>("firms", [], { firmScope: "all" }); const items = useNpdItems();
  const [firmId, setFirmId] = useState(""); const [erp, setErp] = useState(""); const [location, setLocation] = useState(""); const [blockNo, setBlockNo] = useState(""); const [party, setParty] = useState(""); const [item, setItem] = useState(""); const [message, setMessage] = useState("");
  const erpOptions = useMemo(() => (items as Item[]).filter(i => i.erp !== undefined).map(i => ({ value: String(i.erp), label: `${i.erp} — ${i.name}`, searchText: `${i.erp} ${i.name} ${i.customer || ""}` })), [items]);
  const firmOptions = firms.map(f => ({ value: f.id, label: f.firmName })); const locationOptions = locations.filter(l => clean(l.active).toLowerCase() !== "no").map(l => ({ value: l.name, label: l.name }));
  const selectErp = (value: string) => { setErp(value); const found = (items as Item[]).find(i => String(i.erp) === value); setItem(found?.name || ""); setParty(found?.customer || ""); };
  const save = async () => { setMessage(""); const firm = firms.find(f => f.id === firmId); if (!firmId || !erp || !location || !blockNo.trim()) return setMessage("Firm, ERP Code, Block Location, and Block No. are required."); const row: QcBlockRecord = { id: `BLOCK-${Date.now()}-${Math.random().toString(36).slice(2,7)}`, firmId, firmName: firm?.firmName, erpCode: erp, partyName: party, itemName: item, blockLocation: location, blockNo: blockNo.trim(), updatedBy: "System User", updateTimestamp: new Date().toISOString() }; try { await api.addItem(row); setErp(""); setLocation(""); setBlockNo(""); setParty(""); setItem(""); setMessage("Block record saved successfully."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save block record."); } };
  return <div className="space-y-4"><h2 className="border-b border-black pb-3 text-xl font-bold uppercase">Block Record</h2>{message && <div className="rounded border border-black bg-amber-100 p-3 font-bold">{message}</div>}<div className="grid grid-cols-1 gap-3 rounded border-2 border-black bg-white p-4 md:grid-cols-2 xl:grid-cols-4"><label><b>Firm</b><Select value={firmId} onChange={setFirmId} options={firmOptions} placeholder="Select Firm" compact={false}/></label><label><b>ERP Code</b><Select value={erp} onChange={selectErp} options={erpOptions} placeholder="Search ERP Code" compact={false}/></label><label><b>Block Location</b><Select value={location} onChange={setLocation} options={locationOptions} placeholder="Select Location" compact={false}/></label><label><b>Block No.</b><input className={input} value={blockNo} onChange={e => setBlockNo(e.target.value)} placeholder="Block No."/></label><label><b>Party Name</b><input className={`${input} bg-slate-100`} value={party} readOnly/></label><label><b>Item Name</b><input className={`${input} bg-slate-100`} value={item} readOnly/></label><div className="flex items-end"><button type="button" onClick={() => void save()} className="rounded bg-cyan-700 px-5 py-2 font-bold text-white">Save Block Record</button></div></div><div className="overflow-auto rounded border-2 border-black bg-white"><table className="min-w-[850px] w-full text-sm"><thead className="bg-cyan-800 text-white"><tr>{["Sl. No.","Firm","ERP Code","Party Name","Item Name","Location","Block No."].map(h => <th key={h} className="border border-black p-2 text-left">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={7} className="p-5 text-center">Loading...</td></tr> : records.map((r, i) => <tr key={r.id} className="border-t border-black"><td className="p-2">{i + 1}</td><td className="p-2">{r.firmName || firms.find(f => f.id === r.firmId)?.firmName}</td><td className="p-2">{r.erpCode}</td><td className="p-2">{r.partyName}</td><td className="p-2">{r.itemName}</td><td className="p-2">{r.blockLocation}</td><td className="p-2">{r.blockNo}</td></tr>)}</tbody></table></div></div>;
}
