import { useState } from "react";
import { useData } from "../hooks/useData";
import type { QcBlockLocationMaster } from "../types";

export function QcBlockLocationMaster() {
  const [rows, , loading, api] = useData<QcBlockLocationMaster>("qc_block_location_masters", [], { firmScope: "all" });
  const [name, setName] = useState(""); const [editing, setEditing] = useState(""); const [message, setMessage] = useState("");
  const save = async () => { const value = name.trim(); if (!value) return setMessage("Location is required."); const old = rows.find(r => r.id === editing || r.name.toLowerCase() === value.toLowerCase()); const item: QcBlockLocationMaster = { id: old?.id || `BLOCKLOC-${Date.now()}`, name: value, active: old?.active || "Yes", updatedBy: "System User", updateTimestamp: new Date().toISOString() }; try { if (old) await api.saveItem(item); else await api.addItem(item); setName(""); setEditing(""); setMessage("Location saved successfully."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save location."); } };
  const edit = (row: QcBlockLocationMaster) => { setEditing(row.id); setName(row.name); setMessage(""); };
  const toggle = async (row: QcBlockLocationMaster) => { await api.saveItem({ ...row, active: String(row.active).toLowerCase() === "yes" ? "No" : "Yes", updatedBy: "System User", updateTimestamp: new Date().toISOString() }); };
  return <div className="space-y-4"><h2 className="border-b border-black pb-3 text-xl font-bold uppercase">QC Block Location Master</h2>{message && <div className="rounded border border-black bg-amber-100 p-3 font-bold">{message}</div>}<div className="flex gap-2"><input className="rounded border-2 border-black px-3 py-2" value={name} onChange={e => setName(e.target.value)} placeholder="Block Location"/><button type="button" onClick={() => void save()} className="rounded bg-cyan-700 px-4 py-2 font-bold text-white">{editing ? "Update" : "Add"}</button>{editing && <button type="button" onClick={() => { setEditing(""); setName(""); }} className="rounded border-2 border-black px-4 py-2 font-bold">Cancel</button>}</div><div className="overflow-auto rounded border-2 border-black bg-white"><table className="min-w-[500px] w-full text-sm"><thead className="bg-cyan-800 text-white"><tr><th className="p-2 text-left">Location</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Action</th></tr></thead><tbody>{loading ? <tr><td colSpan={3} className="p-5 text-center">Loading...</td></tr> : rows.map(row => <tr key={row.id} className="border-t border-black"><td className="p-2">{row.name}</td><td className="p-2">{String(row.active).toLowerCase() === "yes" ? "Active" : "Inactive"}</td><td className="p-2"><button type="button" onClick={() => edit(row)} className="mr-2 underline">Edit</button><button type="button" onClick={() => void toggle(row)} className="underline">{String(row.active).toLowerCase() === "yes" ? "Deactivate" : "Activate"}</button></td></tr>)}</tbody></table></div></div>;
}
