import { useMemo, useState } from "react";
import { Plus, Search } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import { useData } from "../hooks/useData";
import type { QcSampleRequirement } from "../types";

export function QcSampleRequirementMaster() {
  const navigate = useNavigate();
  const location = useLocation();
  const [rows] = useData<QcSampleRequirement>("qc_sample_requirements", [], { firmScope: "all" });
  const [search, setSearch] = useState("");
  const [firm, setFirm] = useState("");
  const [sales, setSales] = useState("");
  const firms = [...new Set(rows.map(row => row.firmName).filter(Boolean))].sort();
  const salesPeople = [...new Set(rows.map(row => row.salesPerson).filter(Boolean))].sort();
  const filtered = useMemo(() => rows.filter(row => (!firm || row.firmName === firm) && (!sales || row.salesPerson === sales) && (!search || [row.partyName, row.itemName, row.address, row.specialRemarks, row.f1, row.b1, row.f2, row.b2].join(" ").toLowerCase().includes(search.toLowerCase()))), [rows, search, firm, sales]);
  const message = String((location.state as { message?: string } | null)?.message || "");
  const clear = () => { setSearch(""); setFirm(""); setSales(""); };
  return <div className="space-y-4"><div className="flex items-center justify-between border-b border-black pb-3"><h2 className="text-xl font-bold uppercase">Sample Requirement Master</h2><button type="button" onClick={() => navigate("/quality/sample-requirement/master/form")} className="inline-flex items-center gap-2 rounded bg-red-700 px-4 py-2 font-bold text-white"><Plus size={18} />Add</button></div>{message && <div className="rounded border border-black bg-emerald-100 p-3 font-bold">{message}</div>}<div className="grid grid-cols-1 gap-2 rounded border-2 border-black bg-white p-3 md:grid-cols-4"><div className="relative"><Search className="absolute left-2 top-2.5" size={16} /><input className="w-full rounded border border-black py-2 pl-8" placeholder="Search sample..." value={search} onChange={event => setSearch(event.target.value)} /></div><select className="rounded border border-black p-2" value={firm} onChange={event => setFirm(event.target.value)}><option value="">All Firms</option>{firms.map(value => <option key={value}>{value}</option>)}</select><select className="rounded border border-black p-2" value={sales} onChange={event => setSales(event.target.value)}><option value="">All Sales Persons</option>{salesPeople.map(value => <option key={value}>{value}</option>)}</select><button type="button" onClick={clear} className="rounded border-2 border-black font-bold">Clear Filters</button></div><div className="overflow-auto rounded border-2 border-black bg-white"><table className="min-w-[1800px] w-full text-xs"><thead className="bg-red-700 text-white"><tr>{["Receiving Date", "Firm", "Party Name", "Item Name", "Address", "Size", "Ply", "Flute", "GSM", "Quantity", "Required Date", "Spec Received", "Sales Person", "Remarks"].map(header => <th key={header} className="border border-black p-2 text-left">{header}</th>)}</tr></thead><tbody>{filtered.map(row => <tr key={row.id}><td className="border border-black p-2">{row.receivingDate}</td><td className="border border-black p-2">{row.firmName}</td><td className="border border-black p-2">{row.partyName}</td><td className="border border-black p-2">{row.itemName}</td><td className="border border-black p-2">{row.address}</td><td className="border border-black p-2">{[row.length, row.width, row.height].join(" × ")}</td><td className="border border-black p-2">{row.ply}</td><td className="border border-black p-2">{row.flute}</td><td className="border border-black p-2">{row.gsm}</td><td className="border border-black p-2">{row.quantity}</td><td className="border border-black p-2">{row.requiredDate}</td><td className="border border-black p-2">{row.specReceived}</td><td className="border border-black p-2">{row.salesPerson}</td><td className="border border-black p-2">{row.specialRemarks}</td></tr>)}</tbody></table></div></div>;
}
