import { useMemo, useState } from "react";
import { ExternalLink, Search } from "lucide-react";
import { useData } from "../hooks/useData";
import { useNpdItems } from "../hooks/useNpdItems";
import { ExcelExport } from "../components/ExcelExport";
import type { BoardLineQcCheck, PrintingQcCheck, Production } from "../types";

const COLUMNS = ["Job No.", "Date", "Party Name", "Item Name", "ERP Code", "Plan Quantity", "Item Status", "Artwork", "Spec", "Boardline AUTO-CORRECTION Message", "Previous Customer Complaint", "PDI RESULT", "Boardline Production", "Printing Production", "Loaded Quantity", "Length", "Width", "Height", "L-OD", "W-OD", "H-OD", "FLAP", "Ply", "No. Of parts", "SAMPLING PLAN QTY", "Required Size", "Check 1", "Check 2", "Check 3", "Check 4", "Required Cutting Size", "Cutting Check 1", "Cutting Check 2", "Cutting Check 3", "Cutting Check 4", "Required B.GSM", "BGSM MIN", "BGSM MAX", "GSM Check 1", "GSM Check 2", "GSM Check 3", "GSM Check 4", "Flute Check", "Moisture Check", "Board Thickness Achieved", "Board Weight Achieved (Grams)", "QC Remarks"] as const;
type Row = Record<string, string | number>;
const s = (v: unknown) => String(v ?? "").trim(); const key = (v: unknown) => s(v).toLowerCase(); const n = (v: unknown): string | number => v === "" || v == null ? "" : Number.isFinite(Number(v)) ? Number(v) : s(v); const isUrl = (v: unknown) => /^https?:\/\//i.test(s(v));
const LinkCell = ({ value }: { value: unknown }) => isUrl(value) ? <button type="button" onClick={() => window.open(s(value), "_blank", "noopener,noreferrer")} className="inline-flex items-center gap-1 rounded bg-indigo-600 px-2 py-1 font-bold text-white"><ExternalLink size={13} />Open</button> : <>{s(value)}</>;

export function QcView() {
  const [productions] = useData<Production>("productions", [], { firmScope: "all" }); const [boardline] = useData<BoardLineQcCheck>("boardline_qc_checks", []); const [printing] = useData<PrintingQcCheck>("printing_qc_checks", []); const items = useNpdItems();
  const [search, setSearch] = useState(""); const [jobFilter, setJobFilter] = useState(""); const [partyFilter, setPartyFilter] = useState(""); const [itemFilter, setItemFilter] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const [visible, setVisible] = useState<number[]>(() => COLUMNS.map((_, i) => i));
  const rows = useMemo<Row[]>(() => productions.filter((p) => p.status !== "Cancelled" && !(key(p.closeBy) === "yes" && s(p.closeDate))).map((p) => { const job = s(p.transactionNo || p.jobCardNo); const b = boardline.filter((q) => key(q.jobNo) === key(job)).at(-1); const pr = printing.filter((q) => key(q.jobNo) === key(job)).at(-1); const erp = s(p.erpCode || b?.erp || pr?.erp); const item = items.find((i: any) => key(i.id) === key(p.itemId) || key(i.id) === key(p.npdId) || key(i.erp) === key(erp)); const itemName = s((p as any).itemName || item?.name || b?.itemName || pr?.itemName); return { "Job No.": job, Date: s(p.date).slice(0, 10), "Party Name": s(p.companyName || b?.partyName || pr?.partyName), "Item Name": itemName, "ERP Code": erp, "Plan Quantity": n(p.plannedQty || p.qty || b?.planQty || pr?.planQty), "Item Status": s(p.status), Artwork: s(item?.artwork || pr?.standardArtwork || b?.printingArtwork), Spec: s(item?.spec || pr?.standardBoxSize || b?.standard), "Boardline AUTO-CORRECTION Message": [b?.systemAutoCorrection1, b?.systemAutoCorrection2, b?.systemAutoCorrection3, b?.systemAutoCorrection4, b?.systemAutoCorrection5].filter(Boolean).join(" | "), "Previous Customer Complaint": s(b?.previousCustomerComplaintWarning || pr?.previousCustomerComplaintWarning), "PDI RESULT": "", "Boardline Production": n((p as any).prodFromSheetPlant || p.productionOutputQty), "Printing Production": "", "Loaded Quantity": "", Length: n(p.length || b?.length || pr?.lengthId), Width: n(p.breadth || b?.width || pr?.widthId), Height: n(p.height || b?.heightOd || pr?.heightId), "L-OD": n(b?.length), "W-OD": n(b?.width), "H-OD": n(b?.heightOd), FLAP: n(b?.flap), Ply: n(b?.ply), "No. Of parts": s(b?.part), "SAMPLING PLAN QTY": n(b?.samplingPlanQty || pr?.samplingPlanQty), "Required Size": s(pr?.standardBoxSize), "Check 1": n(b?.flapAchievedOs), "Check 2": n(b?.heightAchievedOs), "Check 3": n(b?.flapAchievedDs), "Check 4": n(b?.heightAchievedDs), "Required Cutting Size": n(b?.cuttingSizeRequired), "Cutting Check 1": n(b?.cuttingSizeMm), "Cutting Check 2": "", "Cutting Check 3": "", "Cutting Check 4": "", "Required B.GSM": n(b?.boardGsm), "BGSM MIN": "", "BGSM MAX": "", "GSM Check 1": n(pr?.csAchieved), "GSM Check 2": n(pr?.bsAchieved), "GSM Check 3": "", "GSM Check 4": "", "Flute Check": s(b?.typeOfFlute), "Moisture Check": n(b?.moisture), "Board Thickness Achieved": n(b?.boardThickness || pr?.boardThickness), "Board Weight Achieved (Grams)": n(b?.sheetWeightGrams || pr?.boxWeightGrams), "QC Remarks": s(b?.boardlineRemarks || pr?.column40) }; }).filter((r) => (!jobFilter || r["Job No."] === jobFilter) && (!partyFilter || r["Party Name"] === partyFilter) && (!itemFilter || r["Item Name"] === itemFilter) && (!statusFilter || r["Item Status"] === statusFilter) && (!search.trim() || Object.values(r).some((v) => key(v).includes(key(search))))), [boardline, itemFilter, items, partyFilter, printing, productions, search, statusFilter, jobFilter]);
  const options = useMemo(() => ({ jobs: [...new Set(rows.map((r) => s(r["Job No."])))].sort(), parties: [...new Set(rows.map((r) => s(r["Party Name"])).filter(Boolean))].sort(), items: [...new Set(rows.map((r) => s(r["Item Name"])).filter(Boolean))].sort(), statuses: [...new Set(rows.map((r) => s(r["Item Status"])).filter(Boolean))].sort() }), [rows]); const selected = visible.filter((i) => i < COLUMNS.length); const exportRows = rows.map((r) => Object.fromEntries(selected.map((i) => [COLUMNS[i], r[COLUMNS[i]] ?? ""]))); const clear = () => { setSearch(""); setJobFilter(""); setPartyFilter(""); setItemFilter(""); setStatusFilter(""); };
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-black pb-3"><h2 className="text-xl font-bold uppercase">QC View</h2><ExcelExport data={exportRows} fileName="QC_View" sheetName="QC View" /></div><div className="grid grid-cols-1 gap-2 rounded border border-black bg-white p-3 md:grid-cols-6"><div className="relative md:col-span-2"><Search className="absolute left-2 top-2.5 text-slate-500" size={16} /><input className="w-full rounded border border-black py-2 pl-8 pr-2" placeholder="Search job / party / item / ERP / QC" value={search} onChange={(e) => setSearch(e.target.value)} /></div>{[[jobFilter, setJobFilter, "All Jobs", options.jobs], [partyFilter, setPartyFilter, "All Parties", options.parties], [itemFilter, setItemFilter, "All Items", options.items], [statusFilter, setStatusFilter, "All Statuses", options.statuses]].map(([value, setter, label, values]: any) => <select key={label} value={value} onChange={(e) => setter(e.target.value)} className="rounded border border-black p-2 text-sm"><option value="">{label}</option>{values.map((v: string) => <option key={v}>{v}</option>)}</select>)}<button type="button" onClick={clear} className="rounded border border-black px-3 py-2 font-bold">Clear Filters</button><details className="relative"><summary className="cursor-pointer rounded border border-black px-3 py-2 font-bold">Columns ({selected.length}/{COLUMNS.length})</summary><div className="absolute right-0 z-20 mt-1 max-h-96 w-80 overflow-auto rounded border-2 border-black bg-white p-3 shadow-lg">{COLUMNS.map((column, i) => <label key={column} className="flex items-center gap-2 py-1 text-xs"><input type="checkbox" checked={selected.includes(i)} onChange={() => setVisible((v) => v.includes(i) ? v.filter((x) => x !== i) : [...v, i].sort((a, b) => a - b))} /><span>{column}</span></label>)}</div></details></div><div className="overflow-auto rounded border-2 border-black bg-white"><table className="min-w-[2600px] border-collapse text-[11px]"><thead><tr className="bg-cyan-800 text-white">{selected.map((i) => <th key={COLUMNS[i]} className="whitespace-nowrap border border-black px-2 py-2 text-left">{COLUMNS[i]}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, ri) => <tr key={`${row["Job No."]}-${ri}`} className="odd:bg-white even:bg-slate-50">{selected.map((i) => <td key={COLUMNS[i]} className="whitespace-nowrap border border-black px-2 py-2">{COLUMNS[i] === "Artwork" || COLUMNS[i] === "Spec" ? <LinkCell value={row[COLUMNS[i]]} /> : row[COLUMNS[i]] ?? ""}</td>)}</tr>) : <tr><td colSpan={selected.length || 1} className="p-8 text-center">No open QC jobs found.</td></tr>}</tbody></table></div></div>;
}
