import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import { useData } from "../hooks/useData";
import { ExcelExport } from "../components/ExcelExport";
import type { BoardLineQcCheck, PrintingQcCheck, Production } from "../types";

const COLUMNS = ["Job No.", "Date", "Party Name", "Item Name", "ERP Code", "Plan Quantity", "Item Status", "Artwork", "Spec", "Boardline AUTO-CORRECTION Message", "Previous Customer Complaint", "PDI RESULT", "Boardline Production", "Printing Production", "Loaded Quantity", "Length", "Width", "Height", "L-OD", "W-OD", "H-OD", "FLAP", "Ply", "No. Of parts", "SAMPLING PLAN QTY", "Required Size", "Check 1", "Check 2", "Check 3", "Check 4", "Required Cutting Size", "Cutting Check 1", "Cutting Check 2", "Cutting Check 3", "Cutting Check 4", "Required B.GSM", "BGSM MIN", "BGSM MAX", "GSM Check 1", "GSM Check 2", "GSM Check 3", "GSM Check 4", "Flute Check", "Moisture Check", "Board Thickness Achieved", "Board Weight Achieved (Grams)", "QC Remarks"] as const;
type Row = Record<string, string | number>;
const s = (v: unknown) => String(v ?? "").trim();
const n = (v: unknown): string | number => v === "" || v == null ? "" : Number.isFinite(Number(v)) ? Number(v) : s(v);
const match = (a: unknown, b: unknown) => s(a).toLowerCase() === s(b).toLowerCase();

export function QcView() {
  const [productions] = useData<Production>("productions", [], { firmScope: "all" });
  const [boardline] = useData<BoardLineQcCheck>("boardline_qc_checks", []);
  const [printing] = useData<PrintingQcCheck>("printing_qc_checks", []);
  const [search, setSearch] = useState("");
  const [visible, setVisible] = useState<number[]>(() => COLUMNS.map((_, i) => i));
  const rows = useMemo<Row[]>(() => productions.filter((p) => p.status !== "Cancelled" && !(s(p.closeBy).toLowerCase() === "yes" && s(p.closeDate))).map((p) => {
    const job = s(p.transactionNo || p.jobCardNo);
    const b = boardline.filter((q) => match(q.jobNo, job)).at(-1);
    const pr = printing.filter((q) => match(q.jobNo, job)).at(-1);
    const row: Row = {
      "Job No.": job, Date: s(p.date).slice(0, 10), "Party Name": s(p.companyName || b?.partyName || pr?.partyName), "Item Name": s((p as any).itemName || b?.itemName || pr?.itemName), "ERP Code": s(p.erpCode || b?.erp || pr?.erp), "Plan Quantity": n(p.plannedQty || p.qty || b?.planQty || pr?.planQty), "Item Status": s(p.status), Artwork: s(pr?.standardArtwork || b?.printingArtwork), Spec: s(pr?.standardBoxSize || b?.standard), "Boardline AUTO-CORRECTION Message": [b?.systemAutoCorrection1, b?.systemAutoCorrection2, b?.systemAutoCorrection3, b?.systemAutoCorrection4, b?.systemAutoCorrection5].filter(Boolean).join(" | "), "Previous Customer Complaint": s(b?.previousCustomerComplaintWarning || pr?.previousCustomerComplaintWarning), "PDI RESULT": "", "Boardline Production": n((p as any).prodFromSheetPlant || p.productionOutputQty), "Printing Production": "", "Loaded Quantity": "", Length: n(p.length || b?.length || pr?.lengthId), Width: n(p.breadth || b?.width || pr?.widthId), Height: n(p.height || b?.heightOd || pr?.heightId), "L-OD": n(b?.length), "W-OD": n(b?.width), "H-OD": n(b?.heightOd), FLAP: n(b?.flap), Ply: n(b?.ply), "No. Of parts": s(b?.part), "SAMPLING PLAN QTY": n(b?.samplingPlanQty || pr?.samplingPlanQty), "Required Size": s(pr?.standardBoxSize), "Check 1": n(b?.flapAchievedOs), "Check 2": n(b?.heightAchievedOs), "Check 3": n(b?.flapAchievedDs), "Check 4": n(b?.heightAchievedDs), "Required Cutting Size": n(b?.cuttingSizeRequired), "Cutting Check 1": n(b?.cuttingSizeMm), "Cutting Check 2": "", "Cutting Check 3": "", "Cutting Check 4": "", "Required B.GSM": n(b?.boardGsm), "BGSM MIN": "", "BGSM MAX": "", "GSM Check 1": n(pr?.csAchieved), "GSM Check 2": n(pr?.bsAchieved), "GSM Check 3": "", "GSM Check 4": "", "Flute Check": s(b?.typeOfFlute), "Moisture Check": n(b?.moisture), "Board Thickness Achieved": n(b?.boardThickness || pr?.boardThickness), "Board Weight Achieved (Grams)": n(b?.sheetWeightGrams || pr?.boxWeightGrams), "QC Remarks": s(b?.boardlineRemarks || pr?.column40),
    }; return row;
  }).filter((row) => !search.trim() || Object.values(row).some((v) => s(v).toLowerCase().includes(search.trim().toLowerCase()))), [boardline, printing, productions, search]);
  const selected = visible.filter((i) => i < COLUMNS.length);
  const exportRows = rows.map((row) => Object.fromEntries(selected.map((i) => [COLUMNS[i], row[COLUMNS[i]] ?? ""])));
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-black pb-3"><h2 className="text-xl font-bold uppercase">QC View</h2><ExcelExport data={exportRows} fileName="QC_View" sheetName="QC View" /></div><div className="flex flex-wrap gap-2 rounded border border-black bg-white p-3"><div className="relative min-w-[280px] flex-1"><Search className="absolute left-2 top-2.5 text-slate-500" size={16} /><input className="w-full rounded border border-black py-2 pl-8 pr-2" placeholder="Search job / party / item / ERP / QC" value={search} onChange={(e) => setSearch(e.target.value)} /></div><details className="relative"><summary className="cursor-pointer rounded border border-black px-3 py-2 font-bold">Columns ({selected.length}/{COLUMNS.length})</summary><div className="absolute right-0 z-20 mt-1 max-h-96 w-80 overflow-auto rounded border-2 border-black bg-white p-3 shadow-lg">{COLUMNS.map((column, i) => <label key={column} className="flex items-center gap-2 py-1 text-xs"><input type="checkbox" checked={selected.includes(i)} onChange={() => setVisible((v) => v.includes(i) ? v.filter((x) => x !== i) : [...v, i].sort((a, b) => a - b))} /><span>{column}</span></label>)}</div></details></div><div className="overflow-auto rounded border-2 border-black bg-white"><table className="min-w-[2600px] border-collapse text-[11px]"><thead><tr className="bg-cyan-800 text-white">{selected.map((i) => <th key={COLUMNS[i]} className="whitespace-nowrap border border-black px-2 py-2 text-left">{COLUMNS[i]}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, ri) => <tr key={`${row["Job No."]}-${ri}`} className="odd:bg-white even:bg-slate-50">{selected.map((i) => <td key={COLUMNS[i]} className="whitespace-nowrap border border-black px-2 py-2">{row[COLUMNS[i]] ?? ""}</td>)}</tr>) : <tr><td colSpan={selected.length || 1} className="p-8 text-center">No open QC jobs found.</td></tr>}</tbody></table></div></div>;
}
