import { FormEvent, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, RotateCcw, Save, Search } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import { Select } from "../components/Select";
import { useAuth } from "../auth/AuthContext";
import { useData } from "../hooks/useData";
import { useNpdItems } from "../hooks/useNpdItems";
import type { SpecialRemarkRecord } from "../types";

const input = "w-full rounded border-2 border-black bg-white px-3 py-2";
const today = () => new Date().toISOString().slice(0, 10);
const text = (value: unknown) => String(value ?? "").trim();

export function SpecialRemarkForm() {
  const navigate = useNavigate(); const { user } = useAuth(); const items = useNpdItems();
  const [, , , api] = useData<SpecialRemarkRecord>("special_remark_records", [], { firmScope: "all" });
  const displayName = text(user?.name || user?.userId || user?.email);
  const [form, setForm] = useState({ npdId: "", erpCode: "", itemName: "", specialRemarks: "", emailAddress: "", updatedBy: displayName, updateDate: today() });
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const options = useMemo(() => items.map((item: any) => ({ value: text(item.id), label: `${text(item.erp)} - ${text(item.name)}`, searchText: `${text(item.erp)} ${text(item.name)} ${text(item.customer)}` })).filter(option => option.value), [items]);
  const selectNpd = (npdId: string) => { const item = items.find((value: any) => text(value.id) === npdId) as any; setForm(current => ({ ...current, npdId, erpCode: text(item?.erp), itemName: text(item?.name) })); };
  const reset = () => { setForm({ npdId: "", erpCode: "", itemName: "", specialRemarks: "", emailAddress: "", updatedBy: displayName, updateDate: today() }); setMessage(""); setError(""); };
  const save = async (event: FormEvent) => { event.preventDefault(); setError(""); setMessage(""); if (!form.npdId || !form.erpCode || !form.itemName || !form.specialRemarks.trim()) return setError("ERP/NPD and Special Remarks are required."); if (form.emailAddress && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.emailAddress.trim())) return setError("Enter a valid email address."); setSaving(true); try { await api.addItem({ ...form, id: crypto.randomUUID(), specialRemarks: form.specialRemarks.trim(), emailAddress: form.emailAddress.trim(), updateTimestamp: new Date().toISOString() }); navigate("/quality/special-remarks", { state: { message: "Special Remark saved successfully." } }); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to save Special Remark."); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-4xl space-y-5 pb-8"><div className="flex items-center justify-between border-b border-black pb-3"><h2 className="text-xl font-bold uppercase">Special Remark Form</h2><button type="button" onClick={() => navigate("/quality/special-remarks")} className="inline-flex items-center gap-2 rounded border-2 border-black bg-white px-4 py-2 font-bold"><ArrowLeft size={17}/>Back</button></div>{message && <div className="flex items-center gap-2 rounded border border-emerald-700 bg-emerald-100 p-3 font-bold text-emerald-900"><CheckCircle2 size={18}/>{message}</div>}{error && <div className="rounded border border-red-700 bg-red-100 p-3 font-bold text-red-900">{error}</div>}<form onSubmit={save} className="space-y-5"><section className="rounded border-2 border-black bg-white p-4"><h3 className="mb-4 bg-cyan-800 p-3 font-bold uppercase text-white">Special Remark Details</h3><div className="grid grid-cols-1 gap-4"><label className="space-y-1"><b>ERP Code / NPD *</b><Select value={form.npdId} onChange={selectNpd} options={options} placeholder="Search ERP or Item Name"/></label><label className="space-y-1"><b>Special Remarks *</b><textarea className={`${input} min-h-32`} value={form.specialRemarks} onChange={event => setForm(current => ({ ...current, specialRemarks: event.target.value }))}/></label><label className="space-y-1 md:max-w-md"><b>Email Address</b><input type="email" className={input} value={form.emailAddress} onChange={event => setForm(current => ({ ...current, emailAddress: event.target.value }))}/></label></div></section><div className="flex flex-col gap-3 border-t-2 border-black pt-4 sm:flex-row sm:items-center sm:justify-end"><button type="submit" disabled={saving} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded bg-cyan-700 px-5 py-3 font-bold text-white disabled:cursor-wait disabled:opacity-60 sm:w-auto"><Save size={17}/>{saving ? "Saving..." : "Save Special Remark"}</button><button type="button" onClick={reset} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded border-2 border-black bg-white px-5 py-3 font-bold sm:w-auto"><RotateCcw size={17}/>Clear</button></div></form></div>;
}

export function SpecialRemarkMaster() {
  const location = useLocation(); const [records, , loading] = useData<SpecialRemarkRecord>("special_remark_records", [], { firmScope: "all" }); const [search, setSearch] = useState("");
  const message = text((location.state as { message?: string } | null)?.message); const latest = useMemo(() => { const map = new Map<string, SpecialRemarkRecord>(); records.forEach(record => { const key = text(record.erpCode).toLowerCase(); const old = map.get(key); if (!old || text(record.updateTimestamp || record.updateDate) > text(old.updateTimestamp || old.updateDate)) map.set(key, record); }); const query = search.toLowerCase().trim(); return [...map.values()].filter(record => !query || `${record.erpCode} ${record.itemName} ${record.specialRemarks} ${record.emailAddress || ""}`.toLowerCase().includes(query)).sort((a, b) => text(a.erpCode).localeCompare(text(b.erpCode))); }, [records, search]);
  return <div className="space-y-5 pb-8"><div className="flex items-center justify-between border-b border-black pb-3"><h2 className="text-xl font-bold uppercase">Special Remark Master</h2></div>{message && <div className="rounded border border-emerald-700 bg-emerald-100 p-3 font-bold text-emerald-900">{message}</div>}<div className="flex gap-3 rounded border-2 border-black bg-white p-3"><div className="relative w-full max-w-xl"><Search className="absolute left-3 top-2.5 text-slate-500" size={18}/><input className="w-full rounded border-2 border-black py-2 pl-10 pr-3" placeholder="Search ERP, item, remark, email..." value={search} onChange={event => setSearch(event.target.value)}/></div></div><div className="overflow-auto rounded border-2 border-black bg-white"><table className="min-w-[900px] w-full border-collapse text-sm"><thead className="bg-cyan-800 text-white"><tr>{["ERP Code","Item Name","Special Remarks","Email Address","Update Date"].map(header => <th key={header} className="border border-black p-2 text-left">{header}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={5} className="p-6 text-center">Loading...</td></tr> : latest.length ? latest.map(record => <tr key={record.id}><td className="border border-black p-2 font-bold">{record.erpCode}</td><td className="border border-black p-2">{record.itemName}</td><td className="border border-black p-2 whitespace-pre-wrap">{record.specialRemarks}</td><td className="border border-black p-2">{record.emailAddress || "-"}</td><td className="border border-black p-2">{record.updateDate}</td></tr>) : <tr><td colSpan={5} className="p-6 text-center">No Special Remark records found.</td></tr>}</tbody></table></div></div>;
}
