import React, { useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { Download, RotateCcw } from "lucide-react";
import { useData } from "../hooks/useData";
import type { Production, ProductionProcessing } from "../types";
import { formatDate } from "../lib/serial";
import { buildProductionWastageRows, summarizeProductionWastageRows } from "../lib/wastageReport";

const qty = (v: unknown) => Number(v || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 });
const cell = (v: unknown) => Number(v || 0).toFixed(2);

export function WastageReport() {
  const [processing] = useData<ProductionProcessing>("production_processing", [], { firmScope: "all", storageKey: "production-processing-wastage-report" });
  const [productions] = useData<Production>("productions", []);
  const [search, setSearch] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [machine, setMachine] = useState("");
  const rows = useMemo(() => buildProductionWastageRows(processing, productions, { searchTerm: search, fromDate: from, toDate: to, machine }), [processing, productions, search, from, to, machine]);
  const summary = useMemo(() => summarizeProductionWastageRows(rows), [rows]);
  const exportRows = rows.map((r, i) => ({ "SL No": i + 1, Date: formatDate(r.date), Source: r.source, "Job No": r.jobNo, Item: r.itemName, ERP: r.erp, "Actual Paper Used KG": r.actualPaperUsedKg, "Full Corrugation Qty": r.fullCorrugationQty, "Paper KG/Box": r.paperKgPerBox, "No Hisab Boxes": r.noHisabBoxes, "No Hisab KG": r.noHisabKg, "Sheet Plant Wastage KG": r.sheetPlantWastageKg, "P Wastage Boxes": r.pWastageBoxes, "P Wastage KG": r.pWastageKg, "Total C Wastage KG": r.totalCWastageKg, "Total Wastage %": r.totalWastagePercent, "Warpage Boxes": r.warpageBoxes, "Warpage KG": r.warpageKg, "Delamination Boxes": r.delaminationBoxes, "Delamination KG": r.delaminationKg, "Misalignment Boxes": r.misalignmentBoxes, "Misalignment KG": r.misalignmentKg, "Sheer Cutter Boxes": r.sheerCutterBoxes, "Sheer Cutter KG": r.sheerCutterKg, "2-Ply/Paper KG": r.twoPlyPaperKg, "Deckel KG": r.deckelWastageKg, Slotting: r.slotting, "Delamination Printing": r.delaminationPrinting, "Misalignment Printing": r.misalignmentPrinting, "Dry Sheets": r.drySheets, Warp: r.warp, Misprinting: r.misprinting, "Job Setting": r.jobSetting }));
  const exportExcel = () => { const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet([{ Metric: "Total C Wastage KG", Value: summary.totalCWastageKg }, { Metric: "P Wastage Boxes", Value: summary.pWastageBoxes }, { Metric: "P Wastage KG", Value: summary.pWastageKg }, { Metric: "Total Wastage %", Value: summary.totalWastagePercent }, { Metric: "Records", Value: summary.recordCount }]), "Summary"); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(exportRows), "Wastage"); XLSX.writeFile(wb, "Wastage_Report.xlsx"); };
  const clear = () => { setSearch(""); setFrom(""); setTo(""); setMachine(""); };
  return <div className="space-y-4"><h2 className="border-b border-black pb-3 text-xl font-bold uppercase">Production Wastage Report</h2>
    <div className="grid gap-3 md:grid-cols-5"><Card label="Total C Wastage KG" value={cell(summary.totalCWastageKg)} /><Card label="P Wastage Boxes" value={qty(summary.pWastageBoxes)} /><Card label="P Wastage KG" value={cell(summary.pWastageKg)} /><Card label="Total Wastage %" value={cell(summary.totalWastagePercent) + "%"} /><Card label="Records" value={qty(summary.recordCount)} /></div>
    <div className="rounded border border-black bg-white p-3 flex flex-wrap gap-2"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search job, item, ERP, operator..." className="min-w-[260px] flex-1 rounded border-2 border-black px-3 py-2" /><input type="date" value={from} onChange={e => setFrom(e.target.value)} className="rounded border-2 border-black px-3 py-2" /><input type="date" value={to} onChange={e => setTo(e.target.value)} className="rounded border-2 border-black px-3 py-2" /><select value={machine} onChange={e => setMachine(e.target.value)} className="rounded border-2 border-black px-3 py-2"><option value="">All Sources</option><option>Corrugation Liner</option><option>Printing</option></select><button onClick={clear} className="rounded border border-black px-3 py-2 font-bold"><RotateCcw size={14} /></button><button onClick={exportExcel} className="inline-flex items-center gap-2 rounded border border-emerald-700 bg-emerald-50 px-3 py-2 font-bold text-emerald-800"><Download size={14} />Excel</button></div>
    <div className="overflow-auto rounded border-2 border-black bg-white"><table className="min-w-[3000px] w-full border-collapse text-[11px]"><thead><tr className="bg-indigo-700 text-white">{["Date","Source","Job No","Item / ERP","Actual Paper KG","Full Corr Qty","Paper KG/Box","No Hisab Boxes","No Hisab KG","Sheet Plant Wastage KG","P Wastage Boxes","P Wastage KG","Total C Wastage KG","Total Wastage %","Warpage B/KG","Delamination B/KG","Misalignment B/KG","Sheer Cutter B/KG","2-Ply/Paper KG","Deckel KG","Slotting","Delam Print","Misalign Print","Dry Sheets","Warp","Misprinting","Job Setting"].map(h => <th key={h} className="border border-black px-2 py-2 font-black">{h}</th>)}</tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={27} className="p-8 text-center">No wastage records found.</td></tr> : rows.map(r => <tr key={r.id}><td className="border border-black px-2 py-2">{formatDate(r.date)}</td><td className="border border-black px-2 py-2">{r.source}</td><td className="border border-black px-2 py-2">{r.jobNo}</td><td className="border border-black px-2 py-2">{r.itemName} / {r.erp || "-"}</td>{[r.actualPaperUsedKg,r.fullCorrugationQty,r.paperKgPerBox,r.noHisabBoxes,r.noHisabKg,r.sheetPlantWastageKg,r.pWastageBoxes,r.pWastageKg,r.totalCWastageKg].map((v,i)=><td key={i} className="border border-black px-2 py-2 text-right">{cell(v)}</td>)}<td className="border border-black px-2 py-2 text-right">{cell(r.totalWastagePercent)}%</td><td className="border border-black px-2 py-2 text-right">{cell(r.warpageBoxes)} / {cell(r.warpageKg)}</td><td className="border border-black px-2 py-2 text-right">{cell(r.delaminationBoxes)} / {cell(r.delaminationKg)}</td><td className="border border-black px-2 py-2 text-right">{cell(r.misalignmentBoxes)} / {cell(r.misalignmentKg)}</td><td className="border border-black px-2 py-2 text-right">{cell(r.sheerCutterBoxes)} / {cell(r.sheerCutterKg)}</td>{[r.twoPlyPaperKg,r.deckelWastageKg,r.slotting,r.delaminationPrinting,r.misalignmentPrinting,r.drySheets,r.warp,r.misprinting,r.jobSetting].map((v,i)=><td key={i} className="border border-black px-2 py-2 text-right">{cell(v)}</td>)}</tr>)}</tbody></table></div></div>;
}
function Card({ label, value }: { label: string; value: string }) { return <div className="rounded border border-cyan-300 bg-cyan-50 p-4 text-cyan-900"><div className="text-xs font-black uppercase">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>; }
