import React, { useMemo, useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { Download, FileText, RotateCcw, Search } from "lucide-react";
import { useData } from "../hooks/useData";
import type { Production, ProductionProcessing } from "../types";
import { formatDate } from "../lib/serial";
import { buildProductionWastageRows, summarizeProductionWastageRows, type ProductionWastageRow } from "../lib/wastageReport";

const n = (v: unknown) => Number(v || 0).toLocaleString("en-IN", { maximumFractionDigits: 2 });
const money = (v: unknown) => Number(v || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const value = (row: ProductionWastageRow, key: keyof ProductionProcessing) => row.source === "Corrugation Liner" && ["slotting", "delaminationPrinting", "misalignmentPrinting", "drySheets", "warp", "misprinting", "jobSetting"].includes(String(key)) || row.source === "Printing" && ["warpageBoxes", "warpageKg", "delaminationBoxes", "delaminationKg", "misalignmentBoxes", "misalignmentKg", "sheerCutterBoxes", "sheerCutterKg", "noHisabBoxes", "twoPlyPaperKg", "deckelWastageKg"].includes(String(key)) ? "-" : n(row[key]);

export function WastageReport() {
  const [processing] = useData<ProductionProcessing>("production_processing", [], { firmScope: "all", storageKey: "production-processing-wastage-report" });
  const [productions] = useData<Production>("productions", []);
  const [search, setSearch] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [machine, setMachine] = useState("");
  const rows = useMemo(() => buildProductionWastageRows(processing, productions, { searchTerm: search, fromDate: from, toDate: to, machine }), [processing, productions, search, from, to, machine]);
  const summary = useMemo(() => summarizeProductionWastageRows(rows), [rows]);
  const clear = () => { setSearch(""); setFrom(""); setTo(""); setMachine(""); };
  const exportRows = rows.map((r, i) => ({ "SL No": i + 1, Date: formatDate(r.date), Source: r.source, "Job No": r.jobNo, Item: r.itemName, ERP: r.erp || "-", Shift: r.shift || "-", Operator: r.operatorName, "Production Qty": r.qty, "Warpage Boxes": value(r, "warpageBoxes"), "Warpage KG": value(r, "warpageKg"), "Delamination Boxes": value(r, "delaminationBoxes"), "Delamination KG": value(r, "delaminationKg"), "Misalignment Boxes": value(r, "misalignmentBoxes"), "Misalignment KG": value(r, "misalignmentKg"), "Sheer Cutter Boxes": value(r, "sheerCutterBoxes"), "Sheer Cutter KG": value(r, "sheerCutterKg"), "No Hisab": value(r, "noHisabBoxes"), "2-Ply/Paper KG": value(r, "twoPlyPaperKg"), "Deckel KG": value(r, "deckelWastageKg"), Slotting: value(r, "slotting"), "Delamination Printing": value(r, "delaminationPrinting"), "Misalignment Printing": value(r, "misalignmentPrinting"), "Dry Sheets": value(r, "drySheets"), Warp: value(r, "warp"), Misprinting: value(r, "misprinting"), "Job Setting": value(r, "jobSetting") }));
  const excel = () => { const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet([{ Metric: "Corrugation KG", Value: summary.corrugationKg }, { Metric: "Corrugation Boxes", Value: summary.corrugationBoxes }, { Metric: "Printing Boxes", Value: summary.printingBoxes }, { Metric: "Production Qty", Value: summary.productionQty }, { Metric: "Record Count", Value: summary.recordCount }]), "Summary"); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(exportRows), "Wastage"); XLSX.writeFile(wb, "Wastage_Report.xlsx"); };
  const pdf = () => { const doc = new jsPDF("l", "mm", "a4"); doc.text("Production Wastage Report", 14, 14); autoTable(doc, { head: [["Date", "Source", "Job", "Item", "ERP", "Shift", "Operator", "Qty", "Warpage B", "Warpage KG", "Delam. B", "Delam. KG", "Misalign. B", "Misalign. KG", "Sheer B", "Sheer KG", "No Hisab", "2-Ply KG", "Deckel KG", "Slotting", "Delam. Print", "Misalign. Print", "Dry Sheets", "Warp", "Misprinting", "Job Setting"]], body: rows.map(r => [formatDate(r.date), r.source, r.jobNo, r.itemName, r.erp || "-", r.shift || "-", r.operatorName, n(r.qty), value(r, "warpageBoxes"), value(r, "warpageKg"), value(r, "delaminationBoxes"), value(r, "delaminationKg"), value(r, "misalignmentBoxes"), value(r, "misalignmentKg"), value(r, "sheerCutterBoxes"), value(r, "sheerCutterKg"), value(r, "noHisabBoxes"), value(r, "twoPlyPaperKg"), value(r, "deckelWastageKg"), value(r, "slotting"), value(r, "delaminationPrinting"), value(r, "misalignmentPrinting"), value(r, "drySheets"), value(r, "warp"), value(r, "misprinting"), value(r, "jobSetting")]), startY: 20, styles: { fontSize: 5, cellPadding: 1 }, headStyles: { fillColor: [35, 52, 78] }, horizontalPageBreak: true }); doc.save("Wastage_Report.pdf"); };
  return <div className="space-y-4"><div className="flex flex-col gap-2 border-b border-black pb-3"><h2 className="text-xl font-bold uppercase tracking-tight">Production Wastage Report</h2></div>
    <div className="grid gap-3 md:grid-cols-5"><Card label="Corrugation KG" value={n(summary.corrugationKg)} /><Card label="Corrugation Boxes" value={n(summary.corrugationBoxes)} /><Card label="Printing Boxes" value={n(summary.printingBoxes)} /><Card label="Production Qty" value={n(summary.productionQty)} /><Card label="Records" value={n(summary.recordCount)} /></div>
    <div className="rounded border border-black bg-white p-3"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_repeat(2,130px)_180px_repeat(3,auto)] xl:items-center"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search job, item, ERP, operator..." className="w-full rounded border-2 border-black py-2.5 pl-9 pr-3 text-sm" /></div><input type="date" value={from} onChange={e => setFrom(e.target.value)} className="rounded border-2 border-black px-3 py-2.5 text-sm" /><input type="date" value={to} onChange={e => setTo(e.target.value)} className="rounded border-2 border-black px-3 py-2.5 text-sm" /><select value={machine} onChange={e => setMachine(e.target.value)} className="rounded border-2 border-black px-3 py-2.5 text-sm"><option value="">All Sources</option><option value="Corrugation Liner">Corrugation Liner</option><option value="Printing">Printing</option></select><button onClick={clear} className="inline-flex min-h-[42px] items-center justify-center gap-2 rounded border border-black px-3 py-2 text-sm font-bold"><RotateCcw size={14} />Clear</button><button onClick={excel} className="inline-flex min-h-[42px] items-center justify-center gap-2 rounded border border-emerald-700 bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-800"><Download size={14} />Excel</button><button onClick={pdf} className="inline-flex min-h-[42px] items-center justify-center gap-2 rounded border border-rose-700 bg-rose-50 px-3 py-2 text-sm font-bold text-rose-800"><FileText size={14} />PDF</button></div></div>
    <div className="rounded border-2 border-black bg-white shadow-sm"><div className="max-h-[calc(100vh-310px)] overflow-auto"><table className="w-full min-w-[2700px] border-collapse text-[11px]"><thead className="sticky top-0 z-20"><tr className="bg-indigo-700 text-white">{["Date","Source","Job No","Item / ERP","Shift","Operator","Qty","Warpage Boxes","Warpage KG","Delamination Boxes","Delamination KG","Misalignment Boxes","Misalignment KG","Sheer Cutter Boxes","Sheer Cutter KG","No Hisab Boxes","2-Ply/Paper KG","Deckel Wastage KG","Slotting","Delamination Printing","Misalignment Printing","Dry Sheets","Warp","Misprinting","Job Setting"].map(h => <th key={h} className="border-2 border-black px-2 py-3 text-right font-black uppercase">{h}</th>)}</tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={25} className="border-2 border-black px-6 py-10 text-center text-sm font-medium">No wastage records found.</td></tr> : rows.map((r, i) => <tr key={r.id} className={i % 2 ? "bg-slate-50" : "bg-white"}><td className="border-2 border-black px-2 py-2">{formatDate(r.date)}</td><td className="border-2 border-black px-2 py-2 font-bold">{r.source}</td><td className="border-2 border-black px-2 py-2 font-bold">{r.jobNo}</td><td className="border-2 border-black px-2 py-2">{r.itemName} / {r.erp || "-"}</td><td className="border-2 border-black px-2 py-2">{r.shift || "-"}</td><td className="border-2 border-black px-2 py-2">{r.operatorName}</td><td className="border-2 border-black px-2 py-2 text-right">{n(r.qty)}</td>{["warpageBoxes","warpageKg","delaminationBoxes","delaminationKg","misalignmentBoxes","misalignmentKg","sheerCutterBoxes","sheerCutterKg","noHisabBoxes","twoPlyPaperKg","deckelWastageKg","slotting","delaminationPrinting","misalignmentPrinting","drySheets","warp","misprinting","jobSetting"].map(k => <td key={k} className="border-2 border-black px-2 py-2 text-right">{value(r,k as keyof ProductionProcessing)}</td>)}</tr>)}</tbody></table></div></div></div>;
}
function Card({ label, value }: { label: string; value: string }) { return <div className="rounded border border-cyan-300 bg-cyan-50 p-4 text-cyan-900"><div className="text-xs font-black uppercase opacity-80">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>; }
