export function shouldExcludeFirmWiseNpdReceipt(receipt, unitOneFirmId, unitTwoFirmId) {
    const destinationFirmId = String(receipt.destinationFirmId || receipt.firmId || "").trim();
    return Boolean(unitOneFirmId && unitTwoFirmId)
        && String(receipt.sourceFirmId || "").trim() === unitOneFirmId
        && destinationFirmId === unitTwoFirmId
        && String(receipt.autoGenerated || "").trim().toLowerCase() === "yes";
}
