import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { shouldExcludeFirmWiseNpdReceipt } from "./npdReceipt.js";
describe("Unit-II firm-wise NPD receipts", () => {
    const unitOne = "unit-one";
    const unitTwo = "unit-two";
    it("excludes only auto MRRs from Unit-I to Unit-II", () => {
        assert.equal(shouldExcludeFirmWiseNpdReceipt({ sourceFirmId: unitOne, destinationFirmId: unitTwo, autoGenerated: "Yes" }, unitOne, unitTwo), true);
        assert.equal(shouldExcludeFirmWiseNpdReceipt({ sourceFirmId: unitOne, destinationFirmId: unitTwo, autoGenerated: "No" }, unitOne, unitTwo), false);
        assert.equal(shouldExcludeFirmWiseNpdReceipt({ sourceFirmId: unitOne, destinationFirmId: "lnki", autoGenerated: "Yes" }, unitOne, unitTwo), false);
        assert.equal(shouldExcludeFirmWiseNpdReceipt({ sourceFirmId: "lncb", destinationFirmId: unitTwo, autoGenerated: "Yes" }, unitOne, unitTwo), false);
    });
    it("does not exclude a receipt when Unit-I or Unit-II cannot be resolved", () => {
        const receipt = { sourceFirmId: unitOne, firmId: unitTwo, autoGenerated: "Yes" };
        assert.equal(shouldExcludeFirmWiseNpdReceipt(receipt, "", unitTwo), false);
        assert.equal(shouldExcludeFirmWiseNpdReceipt(receipt, unitOne, ""), false);
    });
});
